/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 soccer_ball.gltf --transform
Author: tinmanjuggernaut (https://sketchfab.com/tinmanjuggernaut)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/soccer-ball-88590cf1e42e44bfb85ce3b6b1959648
Title: Soccer Ball
*/

import React, { useRef } from "react"
import { useGLTF } from "@react-three/drei"

export function SoccerBall(props) {
  const { nodes, materials } = useGLTF("/soccer_ball-transformed.glb")
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials["Material.001"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload("/soccer_ball-transformed.glb")
